### ISSUE TITLE
编写Matlab代码规范

### ISSUE THREAD

**Issue by jingxu94** [tdem-lixiu/GA_TEM#12]
收集Matlab编码规范，编写文档并配以标准示例代码

**Comment by jingxu94** [comment]
程旺盛做

**Comment by Oscar-yh** [comment]
refuse


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Jing Xu <notifications@github.com>
发送时间: 2019年4月28日 20:13
收件人: tdem-lixiu/GA_TEM <GA_TEM@noreply.github.com>
抄送: yanghang <1154933806@qq.com>, Assign <assign@noreply.github.com>
主题: 回复：[tdem-lixiu/GA_TEM] 编写Matlab代码规范 (#12)




程旺盛做
