### ISSUE TITLE
调研JSON格式

### ISSUE THREAD

**Issue by jingxu94** [tdem-lixiu/GA_TEM#16]
学习了解JSON格式，考虑我们的数据格式可否转换成JSON来处理，完成下面链接里说明的4个任务：
https://github.com/tdem-lixiu/TDEM_Document/blob/jx_dev/Summarize/Jingx/Task/TransJSON.md

**Comment by ChengWS19** [comment]
收到

**Comment by jingxu94** [comment]
我更新了任务要求，提供了几个链接资源供你们参考学习，fortran-json-python方案经我测试是可行的，剩下的工作交给你们啦

**Comment by 0chk0** [comment]
收到
