### ISSUE TITLE
回复会议问题

### ISSUE THREAD

**Issue by jingxu94** [tdem-lixiu/GA_TEM#9]
这条内容同时也是为了测试issue
Q1：采用python是否会有无法商业化的风险？
Ans1：收集的资料显示PyQt5可以购买其商业授权版，价格550刀。Numpy遵循BSD授权协议，保留授权说明即可，可以闭源使用。Pygraph遵循更宽松的MIT协议。Matplotlib授权比较复杂，还未了解清楚。
Q2：考虑产品主要面向国内用户及团队内部使用，界面菜单是否改为中文？
Ans2：这个实现不费事，只是Label属性的内容
PS：4月28日晚上组织大家简单学习下平台的使用可以不？

**Comment by wtliu5369** [comment]
comment for Ans1: 好的，继续了解清楚所使用的拓展包协议，整理成文档，下次课题组开会时汇报这个问题。

comment for Ans2: 建议直接出中文版，英文版后期定稿后专门翻译

comment for PS： 可以。我一般晚上八点半左右要回家，尽量把时间安排早一些。
